# leftover mercurial cruft — this is a git repo now, .hgignore serves no purpose
rm -f .hgignore

# autotools-generated build machinery (regenerated by ./autogen.sh)
rm -rf autom4te.cache
rm -f aclocal.m4 compile depcomp install-sh missing configure config.h.in stamp-h1

# configure output / actual build products
rm -f config.h config.log config.status
rm -f Makefile src/Makefile data/Makefile data/ui/Makefile
rm -f Makefile.in src/Makefile.in data/Makefile.in data/ui/Makefile.in

# compiled objects + per-file dependency tracking
find . -name '*.o' -delete
rm -rf src/.deps

# intltool/gettext generated po cruft
rm -f po/Makefile po/Makefile.in po/stamp-it po/POTFILES po/LINGUAS
